version: '3.5'

networks:
  carpinchomq:
      name: iasc

services:
  carpincho-mq-a:
    container_name: carpincho-mq-a
    image: carpincho-mq-image
    hostname: carpincho-mq-a
    ports:
      - "5000:5000"
    working_dir: /app
    command: tail -f /dev/null
    networks:
      - carpinchomq

  carpincho-mq-b:
    container_name: carpincho-mq-b
    image: carpincho-mq-image
    hostname: carpincho-mq-b
    ports:
      - "5001:5000"
    working_dir: /app
    command: tail -f /dev/null
    networks:
      - carpinchomq

  carpincho-mq-c:
    container_name: carpincho-mq-c
    image: carpincho-mq-image
    hostname: carpincho-mq-c
    ports:
      - "5002:5000"
    working_dir: /app
    command: tail -f /dev/null
    networks:
      - carpinchomq